[package]
name = "wwb"
version = "0.0.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.42"
ctrlc = "3.5.1"
env_logger = "0.11.8"
fastrand = "2.3.0"
locusts = "0.0.0"
log = "0.4.28"
